internal enum DebugWindowID
{
	STAGE_BLOCK_MANAGER = 0,
	BLOCK_PATH_CONTROLLER = 1,
	LEVEL_INFORMATION = 2,
	PLAYER_INFORMATION = 3,
	CAMERA_MANAGER = 4,
	STAGE_DEBUG_INFORMATION = 5,
	STAGE_DEBUG_INFORMATION2 = 6,
	STAGE_DEBUG_EDIT = 7,
	MENU_DEBUG = 8,
	STAGE_ITEM_MANAGER = 0x8000,
	SOUND_TEST_START = 32769
}
