public enum EffectPlayType
{
	JUMP = 0,
	LAND = 1,
	RUN = 2,
	FAST_RUN = 3,
	ENEMY_S = 4,
	ENEMY_M = 5,
	ENEMY_L = 6,
	ENEMY_GUARD = 7,
	TRAP = 8,
	AIR_TRAP = 9,
	RING = 10,
	SUPER_RING = 11,
	ANIMAL = 12,
	CRYSTAL_A = 13,
	CRYSTAL_B = 14,
	CRYSTAL_C = 0xF,
	CRYSTAL_BIG_A = 0x10,
	CRYSTAL_BIG_B = 17,
	CRYSTAL_BIG_C = 18,
	NUM = 19,
	UNKNOWN = -1
}
