public enum ResourceCategory
{
	OBJECT_RESOURCE = 0,
	OBJECT_PREFAB = 1,
	ENEMY_RESOURCE = 2,
	ENEMY_PREFAB = 3,
	TERRAIN_MODEL = 4,
	STAGE_RESOURCE = 5,
	UI = 6,
	COMMON_EFFECT = 7,
	PLAYER_COMMON = 8,
	CHARA_MODEL = 9,
	CHARA_EFFECT = 10,
	CHAO_MODEL = 11,
	EVENT_RESOURCE = 12,
	QUICK_MODE = 13,
	ETC = 14,
	NUM = 0xF,
	UNKNOWN = -1
}
