namespace Message
{
	internal enum ObjectID
	{
		SPRING_IMPULSE = 24576,
		DASHRING_IMPULSE,
		CANNON_IMPULSE,
		ROULETTECANNON_IMPULSE,
		ABIDE_PLAYER,
		ABIDE_LOCKED_PLAYER,
		EXITABIDE_PLAYER,
		DRAW_RINGS,
		JUMPBOARD_HIT,
		JUMPBOARD_JUMP,
		DEAD,
		START_LAST_CHANCE,
		END_LAST_CHANCE
	}
}
